### ISSUE TITLE
read only access

### ISSUE THREAD

**Issue by genmeblog** [jackrusher/spicerack#10]
Hi, first, thanks for making MapDB wrappings. I wasn't aware it exists.

Quick question: for read only access can I keep opened database around unless JVM is dead? Or should I everytime wrap into `with-open`? What is the proper strategy?

Opening and closing DB to access single value can be inefficient, however currently it's 6ms on my laptop which is perfectly ok.

**Comment by genmeblog** [comment]
Measured with criterium, with default config: ~3ms, with `:read-only true`: ~1ms, not bad. Opened database: ~60us.

**Comment by jackrusher** [comment]
Hey! Nice to see you here.

You can absolutely use `open-database` and keep the handle it returns rather than using `with-open` to avoid the overhead of opening and closing if you have a long-lived connection. The main production code that uses this library creates a dynamic variable to provide the database context to various other functions. :)
